# Generated by Django 5.2.5 on 2025-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_forumpost_mentorshipbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('welcome_title', models.CharField(default='Welcome to Eden Marriage', max_length=200)),
                ('welcome_subtitle', models.TextField(default='Discover the biblical blueprint for a fulfilling marriage.')),
            ],
        ),
    ]
